export class Propiedad {
    constructor(
        public id : string,
        public idpais : string,
        public ciudad : string,
        public comuna : string,
        public calleandnumber : string,
        public idformato : string,
        public uf : string,
        public monedalocal : string,
        public mt2totales : string,
        public mt2construidos : string,
        public idpropiedad : string,
        public modelos : string,
        public lat : string,
        public lng : string,
        public tipoprop : string,
        public videos : string,
        public galeria : string,
        public equipamiento : string,
        public bodega : string,
        public dormitorios : string,
        public banos : string,
        public corredor : string,
        public identrega : string,
        public financiamiento : string,
        public banco : string,
        public dividendo : string,
        public anosplazo : string,
        public ispago : string,
        public fecha : string,
        public orden : string
    ) {}
  }
  